# Generated by Django 3.2 on 2021-08-27 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleaMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제품명')),
                ('price', models.CharField(max_length=100, verbose_name='가격')),
                ('region', models.CharField(max_length=30, verbose_name='지역')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('long', models.FloatField(verbose_name='경도')),
                ('category', models.TextField(choices=[('디지털기기', '디지털기기'), ('생활가전', '생활가전'), ('가구/인테리어', '가구/인테리어'), ('유아동', '유아동'), ('생활/가공식품', '생활/가공식품'), ('스포츠/레저', '스포트/레저'), ('여성잡회/의류', '여성잡화/의류'), ('남성잡화/의류', '남성잡화/의류'), ('뷰티/미용', '뷰티/미용'), ('도서/티켓/음반', '도서/티켓/음반'), ('기타 중고물품', '기타 중고물품')], verbose_name='카테고리')),
                ('pub_date', models.DateTimeField()),
                ('content', models.TextField(verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fleaMarket/', verbose_name='제품 사진')),
                ('file', models.FileField(blank=True, null=True, upload_to='fleaMarket/', verbose_name='첨부 파일')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
